name: api CI/CD

on:
  push:
    branches:
      - main

# Building
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Github
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Run Tests
        run: mvn test

      - name: Build Artifact
        run: mvn package

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          SOURCE: target/*.jar
          TARGET: ~/chat-platform/